version: "3.8"
services:
  frontend:
    build:
      context: ./front_end
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - backend
    networks:
      - docker-network
    ports:
      - 8001:8001
  backend:
    build:
      context: ./back_end
      dockerfile: Dockerfile
    container_name: backend
    networks:
      docker-network:
        aliases:
          - backend
    ports:
      - 5000:5000
networks:
    docker-network: